
name: Update readme

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.TOKEN }}
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-leetcode 
      - name: Run update.py
        run: |
          python update.py
      - name: Commit changes 
        run: |
          git config --global user.name 'de110' 
          git config --global user.email 'skyyks98@gmail.com' 
          git add -A
          git commit -am "auto update README.md" 
      - name: Push changes 
        run: |
          git push
